Neos:
  Neos:
    userInterface:
      editPreviewModes:
        wireframe:
          isEditingMode: TRUE
          isPreviewMode: FALSE
          typoScriptRenderingPath: 'wireframe'
          title: 'Wireframe'
          position: 'end'
    fusion:
      autoInclude:
        'Webandco.Wireframe': TRUE
    nodeTypes:
      groups:
        wireframe:
          position: 300
          label: 'Wireframe'
